"""
SQLAlchemy models for AI Crypto Trading Dashboard.

This module defines the database models for Signal and ChatMessage entities,
with comprehensive accuracy tracking fields for signal performance monitoring.
"""

from datetime import datetime, timezone
from typing import Optional, Dict, Any
from decimal import Decimal, ROUND_HALF_UP

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    Boolean,
    DateTime,
    Text,
    Enum,
    Numeric,
    ForeignKey,
    Index,
    UniqueConstraint,
    CheckConstraint,
)
from sqlalchemy.orm import validates, relationship
from sqlalchemy.ext.hybrid import hybrid_property
import enum

# Initialize SQLAlchemy instance
db = SQLAlchemy()


class SignalType(enum.Enum):
    """Enumeration of possible signal types."""
    BUY = "BUY"
    SELL = "SELL"
    NEUTRAL = "NEUTRAL"
    STRONG_BUY = "STRONG_BUY"
    STRONG_SELL = "STRONG_SELL"


class SignalStatus(enum.Enum):
    """Enumeration of signal statuses."""
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class SignalSource(enum.Enum):
    """Enumeration of signal sources."""
    AI_MODEL = "AI_MODEL"
    TECHNICAL_ANALYSIS = "TECHNICAL_ANALYSIS"
    MARKET_SENTIMENT = "MARKET_SENTIMENT"
    MANUAL = "MANUAL"


class Signal(db.Model):
    """
    Represents a trading signal generated by the AI system.

    Tracks signal details, performance metrics, and accuracy data
    for continuous model improvement and user transparency.

    Attributes:
        id: Primary key
        symbol: Trading pair symbol (e.g., BTC/USDT)
        signal_type: Type of signal (BUY, SELL, etc.)
        entry_price: Recommended entry price
        exit_price: Actual exit price (set when signal completes)
        stop_loss: Stop loss price level
        take_profit: Take profit price level
        confidence: AI model confidence score (0.0 to 1.0)
        status: Current signal status
        source: Signal generation source
        accuracy: Boolean indicating if signal was accurate
        accuracy_score: Numerical accuracy score (0.0 to 1.0)
        profit_loss: Realized profit/loss percentage
        max_drawdown: Maximum drawdown during signal lifetime
        risk_reward_ratio: Risk/reward ratio at entry
        created_at: Signal creation timestamp
        updated_at: Last update timestamp
        completed_at: Signal completion timestamp
        notes: Additional notes or analysis
        metadata_json: Flexible JSON field for additional data
    """

    __tablename__ = "signals"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Core signal data
    symbol = Column(
        String(20),
        nullable=False,
        index=True,
        comment="Trading pair symbol (e.g., BTC/USDT)",
    )
    signal_type = Column(
        Enum(SignalType),
        nullable=False,
        index=True,
        comment="Type of trading signal",
    )
    entry_price = Column(
        Numeric(20, 8),
        nullable=False,
        comment="Recommended entry price",
    )
    exit_price = Column(
        Numeric(20, 8),
        nullable=True,
        comment="Actual exit price when signal completes",
    )
    stop_loss = Column(
        Numeric(20, 8),
        nullable=True,
        comment="Stop loss price level",
    )
    take_profit = Column(
        Numeric(20, 8),
        nullable=True,
        comment="Take profit price level",
    )

    # AI and accuracy fields
    confidence = Column(
        Float,
        nullable=False,
        default=0.5,
        comment="AI model confidence score (0.0 to 1.0)",
    )
    status = Column(
        Enum(SignalStatus),
        nullable=False,
        default=SignalStatus.PENDING,
        index=True,
        comment="Current signal status",
    )
    source = Column(
        Enum(SignalSource),
        nullable=False,
        default=SignalSource.AI_MODEL,
        comment="Signal generation source",
    )
    accuracy = Column(
        Boolean,
        nullable=True,
        comment="Boolean indicating if signal was accurate",
    )
    accuracy_score = Column(
        Float,
        nullable=True,
        comment="Numerical accuracy score (0.0 to 1.0)",
    )

    # Performance metrics
    profit_loss = Column(
        Float,
        nullable=True,
        comment="Realized profit/loss percentage",
    )
    max_drawdown = Column(
        Float,
        nullable=True,
        comment="Maximum drawdown during signal lifetime",
    )
    risk_reward_ratio = Column(
        Float,
        nullable=True,
        comment="Risk/reward ratio at entry",
    )

    # Timestamps
    created_at = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        comment="Signal creation timestamp",
    )
    updated_at = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        comment="Last update timestamp",
    )
    completed_at = Column(
        DateTime,
        nullable=True,
        comment="Signal completion timestamp",
    )

    # Additional data
    notes = Column(
        Text,
        nullable=True,
        comment="Additional notes or analysis",
    )
    metadata_json = Column(
        Text,
        nullable=True,
        comment="Flexible JSON field for additional data",
    )

    # Relationships
    chat_messages = relationship(
        "ChatMessage",
        back_populates="signal",
        lazy="dynamic",
        cascade="all, delete-orphan",
    )

    # Indexes for common queries
    __table_args__ = (
        Index("idx_signals_symbol_status", "symbol", "status"),
        Index("idx_signals_created_at", "created_at"),
        Index("idx_signals_accuracy", "accuracy"),
        Index("idx_signals_confidence", "confidence"),
        CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name="ck_signals_confidence_range",
        ),
        CheckConstraint(
            "accuracy_score IS NULL OR (accuracy_score >= 0.0 AND accuracy_score <= 1.0)",
            name="ck_signals_accuracy_score_range",
        ),
    )

    @validates("symbol")
    def validate_symbol(self, key: str, value: str) -> str:
        """
        Validate and normalize trading symbol.

        Args:
            key: Field name being validated
            value: Symbol value to validate

        Returns:
            Normalized symbol string

        Raises:
            ValueError: If symbol format is invalid
        """
        if not value or not isinstance(value, str):
            raise ValueError("Symbol must be a non-empty string")

        # Normalize symbol format
        value = value.strip().upper()

        # Validate basic symbol format (e.g., BTC/USDT, ETH-BTC)
        if "/" not in value and "-" not in value:
            raise ValueError(
                "Symbol must contain '/' or '-' separator (e.g., BTC/USDT)"
            )

        # Check symbol length
        if len(value) < 3 or len(value) > 20:
            raise ValueError("Symbol length must be between 3 and 20 characters")

        return value

    @validates("confidence")
    def validate_confidence(self, key: str, value: float) -> float:
        """
        Validate confidence score is within acceptable range.

        Args:
            key: Field name being validated
            value: Confidence score to validate

        Returns:
            Validated confidence score

        Raises:
            ValueError: If confidence is out of range
        """
        if value < 0.0 or value > 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")
        return float(value)

    @validates("accuracy_score")
    def validate_accuracy_score(self, key: str, value: Optional[float]) -> Optional[float]:
        """
        Validate accuracy score is within acceptable range.

        Args:
            key: Field name being validated
            value: Accuracy score to validate

        Returns:
            Validated accuracy score or None

        Raises:
            ValueError: If accuracy score is out of range
        """
        if value is not None:
            if value < 0.0 or value > 1.0:
                raise ValueError("Accuracy score must be between 0.0 and 1.0")
            return float(value)
        return None

    @validates("entry_price")
    def validate_entry_price(self, key: str, value: Decimal) -> Decimal:
        """
        Validate entry price is positive.

        Args:
            key: Field name being validated
            value: Entry price to validate

        Returns:
            Validated entry price

        Raises:
            ValueError: If price is not positive
        """
        if value <= 0:
            raise ValueError("Entry price must be positive")
        return value

    @hybrid_property
    def is_active(self) -> bool:
        """
        Check if signal is currently active.

        Returns:
            True if signal status is ACTIVE, False otherwise
        """
        return self.status == SignalStatus.ACTIVE

    @hybrid_property
    def duration_hours(self) -> Optional[float]:
        """
        Calculate signal duration in hours.

        Returns:
            Duration in hours if signal is completed, None otherwise
        """
        if self.completed_at and self.created_at:
            delta = self.completed_at - self.created_at
            return delta.total_seconds() / 3600
        return None

    def calculate_accuracy(self, actual_outcome: bool) -> None:
        """
        Calculate and update accuracy metrics based on actual outcome.

        Args:
            actual_outcome: Boolean indicating if signal was accurate

        Raises:
            ValueError: If signal is not in COMPLETED status
        """
        if self.status != SignalStatus.COMPLETED:
            raise ValueError("Can only calculate accuracy for completed signals")

        self.accuracy = actual_outcome
        self.accuracy_score = 1.0 if actual_outcome else 0.0

        # Update completion timestamp if not set
        if not self.completed_at:
            self.completed_at = datetime.now(timezone.utc)

    def calculate_profit_loss(self, current_price: Decimal) -> float:
        """
        Calculate profit/loss percentage based on current price.

        Args:
            current_price: Current market price

        Returns:
            Profit/loss percentage

        Raises:
            ValueError: If current price is not positive
        """
        if current_price <= 0:
            raise ValueError("Current price must be positive")

        entry = float(self.entry_price)
        current = float(current_price)

        if self.signal_type in (SignalType.BUY, SignalType.STRONG_BUY):
            pl_percentage = ((current - entry) / entry) * 100
        elif self.signal_type in (SignalType.SELL, SignalType.STRONG_SELL):
            pl_percentage = ((entry - current) / entry) * 100
        else:
            pl_percentage = 0.0

        # Round to 2 decimal places
        pl_percentage = float(
            Decimal(str(pl_percentage)).quantize(
                Decimal("0.01"), rounding=ROUND_HALF_UP
            )
        )

        self.profit_loss = pl_percentage
        return pl_percentage

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert signal to dictionary for API responses.

        Returns:
            Dictionary representation of signal
        """
        return {
            "id": self.id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value if self.signal_type else None,
            "entry_price": float(self.entry_price) if self.entry_price else None,
            "exit_price": float(self.exit_price) if self.exit_price else None,
            "stop_loss": float(self.stop_loss) if self.stop_loss else None,
            "take_profit": float(self.take_profit) if self.take_profit else None,
            "confidence": self.confidence,
            "status": self.status.value if self.status else None,
            "source": self.source.value if self.source else None,
            "accuracy": self.accuracy,
            "accuracy_score": self.accuracy_score,
            "profit_loss": self.profit_loss,
            "max_drawdown": self.max_drawdown,
            "risk_reward_ratio": self.risk_reward_ratio,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "notes": self.notes,
            "is_active": self.is_active,
            "duration_hours": self.duration_hours,
        }

    def __repr__(self) -> str:
        """String representation of Signal instance."""
        return (
            f"<Signal(id={self.id}, symbol='{self.symbol}', "
            f"type='{self.signal_type}', status='{self.status}', "
            f"confidence={self.confidence})>"
        )


class ChatMessage(db.Model):
    """
    Represents a chat message in the interactive trading dashboard.

    Stores user messages, AI responses, and associated signal context
    for comprehensive conversation tracking and analysis.

    Attributes:
        id: Primary key
        signal_id: Foreign key to associated signal (optional)
        user_id: User identifier (optional for anonymous users)
        role: Message role (user, assistant, system)
        content: Message content/text
        message_type: Type of message (text, signal_alert, analysis, etc.)
        metadata_json: Flexible JSON field for additional data
        is_read: Whether message has been read
        sentiment: Message sentiment score (-1.0 to 1.0)
        created_at: Message creation timestamp
        updated_at: Last update timestamp
    """

    __tablename__ = "chat_messages"

    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)

    # Foreign keys
    signal_id = Column(
        Integer,
        ForeignKey("signals.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Associated signal ID",
    )

    # User information
    user_id = Column(
        String(100),
        nullable=True,
        index=True,
        comment="User identifier (optional for anonymous users)",
    )

    # Message data
    role = Column(
        String(20),
        nullable=False,
        default="user",
        comment="Message role (user, assistant, system)",
    )
    content = Column(
        Text,
        nullable=False,
        comment="Message content/text",
    )
    message_type = Column(
        String(50),
        nullable=False,
        default="text",
        comment="Type of message (text, signal_alert, analysis, etc.)",
    )
    metadata_json = Column(
        Text,
        nullable=True,
        comment="Flexible JSON field for additional data",
    )

    # Status fields
    is_read = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether message has been read",
    )
    sentiment = Column(
        Float,
        nullable=True,
        comment="Message sentiment score (-1.0 to 1.0)",
    )

    # Timestamps
    created_at = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
        comment="Message creation timestamp",
    )
    updated_at = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        comment="Last update timestamp",
    )

    # Relationships
    signal = relationship(
        "Signal",
        back_populates="chat_messages",
        lazy="joined",
    )

    # Indexes for common queries
    __table_args__ = (
        Index("idx_chat_messages_signal_created", "signal_id", "created_at"),
        Index("idx_chat_messages_user_created", "user_id", "created_at"),
        Index("idx_chat_messages_role", "role"),
        Index("idx_chat_messages_message_type", "message_type"),
        CheckConstraint(
            "sentiment IS NULL OR (sentiment >= -1.0 AND sentiment <= 1.0)",
            name="ck_chat_messages_sentiment_range",
        ),
        CheckConstraint(
            "role IN ('user', 'assistant', 'system')",
            name="ck_chat_messages_valid_role",
        ),
    )

    @validates("role")
    def validate_role(self, key: str, value: str) -> str:
        """
        Validate message role is one of the allowed values.

        Args:
            key: Field name being validated
            value: Role to validate

        Returns:
            Validated role string

        Raises:
            ValueError: If role is invalid
        """
        valid_roles = {"user", "assistant", "system"}
        value = value.strip().lower()

        if value not in valid_roles:
            raise ValueError(f"Role must be one of: {', '.join(valid_roles)}")

        return value

    @validates("content")
    def validate_content(self, key: str, value: str) -> str:
        """
        Validate message content is not empty.

        Args:
            key: Field name being validated
            value: Content to validate

        Returns:
            Validated content string

        Raises:
            ValueError: If content is empty or too long
        """
        if not value or not isinstance(value, str):
            raise ValueError("Message content cannot be empty")

        # Strip whitespace
        value = value.strip()

        if not value:
            raise ValueError("Message content cannot be only whitespace")

        # Limit content length (adjust as needed)
        if len(value) > 10000:
            raise ValueError("Message content exceeds maximum length of 10000 characters")

        return value

    @validates("sentiment")
    def validate_sentiment(self, key: str, value: Optional[float]) -> Optional[float]:
        """
        Validate sentiment score is within acceptable range.

        Args:
            key: Field name being validated
            value: Sentiment score to validate

        Returns:
            Validated sentiment score or None

        Raises:
            ValueError: If sentiment is out of range
        """
        if value is not None:
            if value < -1.0 or value > 1.0:
                raise ValueError("Sentiment must be between -1.0 and 1.0")
            return float(value)
        return None

    @hybrid_property
    def is_signal_alert(self) -> bool:
        """
        Check if message is a signal alert type.

        Returns:
            True if message type is signal_alert, False otherwise
        """
        return self.message_type == "signal_alert"

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert chat message to dictionary for API responses.

        Returns:
            Dictionary representation of chat message
        """
        return {
            "id": self.id,
            "signal_id": self.signal_id,
            "user_id": self.user_id,
            "role": self.role,
            "content": self.content,
            "message_type": self.message_type,
            "is_read": self.is_read,
            "sentiment": self.sentiment,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "is_signal_alert": self.is_signal_alert,
            "signal": self.signal.to_dict() if self.signal else None,
        }

    def __repr__(self) -> str:
        """String representation of ChatMessage instance."""
        return (
            f"<ChatMessage(id={self.id}, role='{self.role}', "
            f"type='{self.message_type}', "
            f"created_at='{self.created_at}')>"
        )


def init_db(app):
    """
    Initialize database with Flask application context.

    Args:
        app: Flask application instance

    Returns:
        SQLAlchemy database instance
    """
    db.init_app(app)

    with app.app_context():
        # Create all tables
        db.create_all()

        # Verify table creation
        inspector = db.inspect(db.engine)
        tables = inspector.get_table_names()
        required_tables = {"signals", "chat_messages"}

        if not required_tables.issubset(set(tables)):
            missing = required_tables - set(tables)
            raise RuntimeError(f"Failed to create database tables: {missing}")

    return db


def get_signal_accuracy_stats(symbol: Optional[str] = None) -> Dict[str, Any]:
    """
    Get accuracy statistics for signals.

    Args:
        symbol: Optional trading symbol to filter by

    Returns:
        Dictionary containing accuracy statistics
    """
    query = Signal.query.filter(Signal.status == SignalStatus.COMPLETED)

    if symbol:
        query = query.filter(Signal.symbol == symbol.upper())

    total_signals = query.count()
    accurate_signals = query.filter(Signal.accuracy == True).count()

    if total_signals > 0:
        accuracy_rate = (accurate_signals / total_signals) * 100
    else:
        accuracy_rate = 0.0

    return {
        "total_signals": total_signals,
        "accurate_signals": accurate_signals,
        "inaccurate_signals": total_signals - accurate_signals,
        "accuracy_rate": round(accuracy_rate, 2),
        "average_confidence": query.with_entities(
            db.func.avg(Signal.confidence)
        ).scalar() or 0.0,
        "average_profit_loss": query.with_entities(
            db.func.avg(Signal.profit_loss)
        ).scalar() or 0.0,
    }